services:
  backend:
    build: ./backend
    environment:
      PORT: 4000
      DATABASE_URL: file:./prisma/dev.db
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    environment:
      VITE_API_URL: "/api"
      VITE_PROXY_TARGET: "http://backend:4000"
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
